version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile # Utilisation d'un Dockerfile pour construire l'image
    container_name: mon-app
    working_dir: /usr/src/app
    volumes:
      - .:/usr/src/app # Synchronisation des fichiers locaux
      - /usr/src/app/node_modules # Exclusion des dépendances locales
    ports:
      - "3000:3000" # Expose le port 3000
    environment:
      - NODE_ENV=production
    command: >
      sh -c "npm install && npm run build && npm start"
