version: '3.8'

services:
  app:
    image: node:16-alpine # Utilisez une version adaptée à votre projet
    container_name: mon-app
    working_dir: /usr/src/app
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules # Assurez-vous que les dépendances sont locales
    ports:
      - "3000:3000" # Port exposé par votre application Node.js
    environment:
      - NODE_ENV=production
    command: >
      sh -c "npm install && npm run build && npm start"
